<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SongRequests-Setup</AssemblyName>
    <ApplicationIcon>..\icon.ico</ApplicationIcon>
    <AssemblyTitle>Song Requests Setup</AssemblyTitle>
    <Product>Song Requests</Product>
    <Company>Goku67HoodWars</Company>
    <Description>Installer for Song Requests</Description>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
